### ISSUE TITLE
Up arrow key misinterpreted as a shortcut for Screenshot

### ISSUE THREAD

**Issue by grahamperrin** [mszoek/airyx#50] opened 2021-05-22 17:47 UTC
Installed from `Helium_0.2.1-F12.2_h0.5.0-amd64.iso`

https://user-images.githubusercontent.com/192271/119236221-22b35580-bb2e-11eb-9546-9759f8001808.mp4

**Comment by mszoek** [comment] 2021-05-22 19:11
Interesting... it must be mapped to the same as Print or Ctrl-Shift-3 (probably Print) by the keyboard layout.

**Comment by probonopd** [comment] 2021-05-23 16:24
I encountered this "Up arrow key misinterpreted as a shortcut for Screenshot" error on FreeBSD/helloSystem earlier but I was never able to find out what was causing it and how to resolve it. I think current helloSystem versions don't suffer from it but don't ask me why ;-/

**Comment by mszoek** [comment] 2021-05-23 17:41
Maybe the fix is in the 13.0 base or package set? It is thankfully easy to work around by removing the shortcut.

**Comment by grahamperrin** [comment] 2021-05-25 04:36
Thanks, 

> removing the shortcut.

– which one?

**Comment by mszoek** [comment] 2021-05-25 22:38
> Thanks,
> 
> > removing the shortcut.
> 
> – which one?

I'm not sure. I suspect the Print one, but the issue is not happening for me.

**Closed** 2021-06-21 23:31 UTC
Labels: GUI, bug
