### ISSUE TITLE
"Open in File Manager" button doesn't open a Filer window

### ISSUE THREAD

**Issue by markshank** [mszoek/airyx#108] opened 2021-09-05 18:26 UTC
I clicked the "Open in File Manager" button and the notification disappeared, but nothing else appeared. 

Refer to original post for details.

**Note:  The system was disk constrained when this issue was observed.**

_Originally posted by @markshank in https://github.com/mszoek/airyx/issues/106#issuecomment-913137627_

**Comment by mszoek** [comment] 2021-09-06 14:39
Can you try right-clicking in the terminal under normal conditions and choosing "Open file manager"? Does it open Filer?

**Comment by markshank** [comment] 2021-09-06 15:09
Yes, it opens a Filer window.

Also, if I Alt-Tab to the black screen and right click to open KRunner.  And then launch Konsole and right click inside its window and choose "Open file manager", I get a Filer window on the black screen.

**Comment by mszoek** [comment] 2021-09-06 17:24
Awesome! Thanks for checking. You were right about the cause so I'll close this :)

**Closed by mszoek** 2021-09-06 17:24 UTC
